### PR TITLE
Add ux and ux review

### PR DESCRIPTION
**Pull request by SteveBarnett**
@avermeulen, @Oyamasiphula, @Onwa2014 review please!

### CODE REVIEW

**Comment by Onwa2014** [comment]
@SteveBarnett  I like so that they have those  10 general principles for interaction design at the back of their mind while they are creating the application :+1:

**Comment by SteveBarnett** [comment]
@Onwa2014 \o/ Yay, thank you :).

**Comment by SteveBarnett** [comment]
@avermeulen review please!

**Comment by avermeulen** [comment]
@SteveBarnett looks 👍  merged

**Pull request merged**
