### PR TITLE
Add tdd test plans

### PR DESCRIPTION
**Pull request by SteveBarnett**
@avermeulen, @Onwa2014, @Oyamasiphula: please review. 

I'm not sure about adding all this here vs adding it in the express intro, express auth, and database mini-sites. My feeling is that keeping it "upstream" is better: less clutter in the details, and keeping it more high level.

What do y'all think?

### CODE REVIEW

**Comment by Onwa2014** [comment]
@SteveBarnett  I don't quite get the testing on **deploy_online101.md** 
You said something about console, do we need to console.log stuff or you are talking about the error message that the terminal will display? Secondly: where is the md, is it on Heroku or it's on your machine like locally? Do I create the file everytime i get an error or it's already there?

**Deploy_roles_login.md**

bcrypt we don't test it but we test the implementation I don't think I get it how maybe is the question I have. What is implementation?

**DB_setup.md**

database test and user. I am totally blank here. Therefore web_basics.md the testing section was affected because i don't understand or I don't know

**Comment by Onwa2014** [comment]
@SteveBarnett  On the question I think it would be best to add  it in the express intro, express auth, and database mini-sites.

**Comment by SteveBarnett** [comment]
@Onwa2014 Thank you for the excellent feedback! 
I've added a few commits in an attempt to clarify some of those things (especially the db testing, with a link to Mocha hooks, which have some examples). Could you have a another look please?

Re into the mini-sites: I was afraid you might say that! :O
What does everyone else think? :)

**Comment by SteveBarnett** [comment]
@avermeulen review please!

**Comment by SteveBarnett** [comment]
@avermeulen  Are you still looking at this? I've pulled in the latest `gh-pages` so it can be merged.

**Comment by avermeulen** [comment]
@SteveBarnett this one I haven't got to yet. I got a sticky on my board for it now.

**Comment by SteveBarnett** [comment]
Closing, but leaving the branch.

**Pull request closed without merging**
