### PR TITLE
Mocha to markdown

### PR DESCRIPTION
**Pull request by SteveBarnett**
Add test "report" things, using mocha to export results to a markdown file.

@avermeulen, @Onwa2014, @Oyamasiphula: review please!

### CODE REVIEW

**Comment by Onwa2014** [comment]
@SteveBarnett  when I am running this command mocha --R markdown > YYYYMMDD-results.md I get this error: unknown option `--R'. I then tried running with a small letter r and I got this error: unknown option`--r'. I removed the > then so I ran this command mocha --r markdown  20160628-results.md it created a blank file. I tried mocha --R markdown 20160627-results.md and I got this error Error: cannot resolve path (or pattern) '20160627-results.md'
    at Object.lookupFiles (/usr/local/lib/node_modules/mocha/lib/utils.js:577:32)
Please look at the commands again if we are not suppose to get a blank file.

**Comment by SteveBarnett** [comment]
@Onwa2014 Good catch, thank you!

I made an error in the docs. You can use `--reporter` or `-R`. But not `--R` 😬 .
I've updated the docs: https://github.com/codex-academy/Nelisa/pull/14/commits/9ed1e498cd6591e3403fba7f82a8a8c465c10bc6

**Comment by SteveBarnett** [comment]
@avermeulen review please!

**Comment by avermeulen** [comment]
@SteveBarnett the section looks good. The markdown reporter itself is a bit weird it is shows the source code of the unit test, but not if the test is failing or passing. Is that the way you had it as well?

**Comment by SteveBarnett** [comment]
@avermeulen Yeah, just a copy of the tests, not the results.
But I think that satisfies the AC, right?

**Pull request merged**
